// <auto-generated />
namespace CacheViewer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingCacheIndexId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingCacheIndexId));
        
        string IMigrationMetadata.Id
        {
            get { return "201806190332561_AddingCacheIndexId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
