// <auto-generated />
namespace CacheViewer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NoClue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoClue));
        
        string IMigrationMetadata.Id
        {
            get { return "201901290414377_NoClue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
