//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowbane.CacheViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowbane.CacheViewer.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CacheIndexDataGridColumnId {
            get {
                return ResourceManager.GetString("CacheIndexDataGridColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string CacheIndexDataGridColumnOffset {
            get {
                return ResourceManager.GetString("CacheIndexDataGridColumnOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawSize.
        /// </summary>
        internal static string CacheIndexDataGridColumnRawSize {
            get {
                return ResourceManager.GetString("CacheIndexDataGridColumnRawSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string CacheIndexDataGridColumnSize {
            get {
                return ResourceManager.GetString("CacheIndexDataGridColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not find a CacheIndex for identy {1}.
        /// </summary>
        internal static string CantFindIndex {
            get {
                return ResourceManager.GetString("CantFindIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a RenderId for CacheObejct {0}..
        /// </summary>
        internal static string CouldNotFindRenderId {
            get {
                return ResourceManager.GetString("CouldNotFindRenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Archive index, one second..
        /// </summary>
        internal static string LoadingArchive {
            get {
                return ResourceManager.GetString("LoadingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Mesh.
        /// </summary>
        internal static string LoadModelButtonText {
            get {
                return ResourceManager.GetString("LoadModelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load time from cache:.
        /// </summary>
        internal static string LoadTimeFromCache {
            get {
                return ResourceManager.GetString("LoadTimeFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh Viewer Form.
        /// </summary>
        internal static string MeshViewerFormTitle {
            get {
                return ResourceManager.GetString("MeshViewerFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenderControl selected item id was {0}, but RenderFactory does not have a matching id!.
        /// </summary>
        internal static string RenderFactoryDoesNotHaveMatchingId {
            get {
                return ResourceManager.GetString("RenderFactoryDoesNotHaveMatchingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This render item had a textureId of 0, exiting..
        /// </summary>
        internal static string RenderTextureId0 {
            get {
                return ResourceManager.GetString("RenderTextureId0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving sound file.
        /// </summary>
        internal static string SoundControl_SaveAllSoundsButtonClick_Saving_sound_file_ {
            get {
                return ResourceManager.GetString("SoundControl_SaveAllSoundsButtonClick_Saving_sound_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find mathching mesh id!.
        /// </summary>
        internal static string UnableToFindMathchingMeshId {
            get {
                return ResourceManager.GetString("UnableToFindMathchingMeshId", resourceCulture);
            }
        }
    }
}
